name: map_camera_flutter
description: The Map Camera flutter package provides a convenient way to capture images with map and location data using the device's camera.

version: 0.1.0
homepage: https://github.com/Always-Bijoy/map_camera_location_flutter

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  url_launcher: ^6.3.1
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
